name: Generate Changelog

on:
  push:
    branches:
      - master

jobs:
  changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Generate Changelog
        run: |
          git log --pretty=format:"- [%h](https://github.com/${GITHUB_USERNAME}/${GITHUB_REPOSITORY}/commit/%h): (%s) ([@%an](https://github.com/%an))" --grep="^feat:" > features.txt
          git log --pretty=format:"- [%h](https://github.com/${GITHUB_USERNAME}/${GITHUB_REPOSITORY}/commit/%h): (%s) ([@%an](https://github.com/%an))" --grep="^fix:" > fixes.txt
          echo "# Changelog" > CHANGELOG.md

          echo "**New Features**" >> CHANGELOG.md
          if [ -s features.txt ]; then
            cat features.txt >> CHANGELOG.md
          else
            echo "- No new features." >> CHANGELOG.md
          fi

          echo "\n**Bug Fixes**" >> CHANGELOG.md
          if [ -s fixes.txt ]; then
            cat fixes.txt >> CHANGELOG.md
          else
            echo "- No new fixes." >> CHANGELOG.md
          fi

          rm features.txt fixes.txt

      - name: Commit and Push Changelog
        run: |
          git add CHANGELOG.md
          git commit -m "chore: update changelog"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "v${{ github.run_number }}"
          release_name: "Release ${{ github.run_number }}"
          body_path: CHANGELOG.md
          draft: false
          prerelease: false
